spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: Complaint_system
      auto-indexing: true

  mail:
    host: smtp.gmail.com
    port: 587
    username:  ${MAIL_USERNAME}
    password:  ${MAIL_PASSWORD}  #ypak lduv egwu stqk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

twilio:
  accountSid: ${TWILIO_ACCOUNT_SID}
  authToken: ${TWILIO_AUTH_TOKEN}
  trialNumber: ${TWILIO_TRIAL_NUMBER}

management:
  endpoints:
    web:
      exposure:
        include: health
  health:
    mongo:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    url: /v3/api-docs
    path: /swagger-ui.html

jwt:
  secret: ${JWT_SECRET} #TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V